Table ALUNO {
  id_aluno INTEGER [pk]
  nm_aluno VARCHAR(255) [not null]
  cd_cpf_aluno CHAR(11) [not null, unique]
  dt_nascimento_aluno DATE [not null]
  nm_email_aluno VARCHAR(255) [not null, unique]
  nm_endereco_aluno VARCHAR(255) [not null]
  cd_situacao_aluno NUMBER(4) [not null]
}

Table PROFESSOR {
  id_professor INTEGER [pk]
  nm_professor VARCHAR(255) [not null]
  cpf_professor CHAR(11) [not null, unique]
  nm_email_professor VARCHAR(255) [not null, unique]
  nm_especialidade_professor VARCHAR(255) [not null]
  dt_admissao_professor DATE [not null]
}

Table CURSO {
  id_curso INTEGER [pk, increment]
  sg_curso CHAR(10) [not null]
  nm_curso VARCHAR(255) [not null]
  ds_curso VARCHAR(255)
  cd_periodo_curso NUMBER(4) [not null]
  qt_carga_horaria_curso NUMBER(4) [not null]
  qt_semestre_curso NUMBER(2) [not null]
  cd_modalidade_curso NUMBER(4) [not null]
  dt_desativacao_curso DATE
}

Table DISCIPLINA {
  id_disciplina INTEGER [pk, increment]
  sg_disciplina CHAR(16) [not null]
  nm_disciplina VARCHAR(255) [not null]
  ds_disciplina VARCHAR(255)
  qt_carga_horaria_disciplina NUMBER(4) [not null]
  dt_desativacao_disciplina DATE
}

Table DISCIPLINA_CURSO {
  id_curso INTEGER [ref: > CURSO.id_curso]
  id_disciplina INTEGER [ref: > DISCIPLINA.id_disciplina]
  id_ciclo_disciplina_curso NUMBER(2)

  indexes {
    (id_curso, id_disciplina, id_ciclo_disciplina_curso) [pk]
  }
}

Table GRADE_CURSO {
  dd_semana_grade_curso CHAR(3) [not null]
  hr_inicio_grade_curso NUMBER(4) [not null] // NUMBER(4): minutos depois da meia noite
  cd_sala_grade_curso VARCHAR(20) [not null]
  id_ciclo_disciplina_curso NUMBER(2) [not null]
  id_curso INTEGER [not null]
  id_disciplina INTEGER [not null]

  indexes {
    (dd_semana_grade_curso, hr_inicio_grade_curso,cd_sala_grade_curso) [pk]
  }
}
Ref: GRADE_CURSO.(id_curso,id_disciplina,id_ciclo_disciplina_curso) > DISCIPLINA_CURSO.(id_curso,id_disciplina,id_ciclo_disciplina_curso)

Table PERIODO_LETIVO {
  id_periodo_letivo INTEGER [pk]
  aa_periodo_letivo NUMBER(4) [not null]
  semestre_periodo_letivo NUMBER(1) [not null]
  indexes {
    (aa_periodo_letivo,semestre_periodo_letivo) [unique]
  }
  checks {
    `semestre_periodo_letivo IN (1,2)` [name: 'chk_semestre']
  }
}

Table TURMA {
  id_turma INTEGER [pk]
  id_ciclo_turma NUMBER(2) [not null]
  qt_vagas_turma NUMBER(3) [not null]

  id_curso INTEGER [not null]
  id_disciplina INTEGER [not null]
  id_ciclo_disciplina_curso NUMBER(2) [not null]
  id_periodo_letivo INTEGER [not null, ref: > PERIODO_LETIVO.id_periodo_letivo]
  id_professor INTEGER [not null, ref: > PROFESSOR.id_professor]
}
Ref: TURMA.(id_curso,id_disciplina,id_ciclo_disciplina_curso) > DISCIPLINA_CURSO.(id_curso,id_disciplina,id_ciclo_disciplina_curso)

Table MATRICULA {
  id_matricula INTEGER [pk]
  id_turma INTEGER [not null, ref: > TURMA.id_turma]
  id_aluno INTEGER [not null, ref: > ALUNO.id_aluno]
  INDEXES {
    (id_turma, id_aluno) [unique]
  }
}

Table GRADE_TURMA {
  id_grade_turma INTEGER [pk]
  dd_semana_grade_turma CHAR(3) [not null]
  hr_inicio_grade_turma NUMBER(4) [not null, check: `hr_inicio_grade_turma BETWEEN 0 AND 1440`] // NUMBER(4): minutos depois da meia noite
  cd_sala_grade_turma VARCHAR(20) [not null]
  id_turma INTEGER [not null, ref: > TURMA.id_turma]

  checks {
    `dd_semana_grade_turma IN ('SEG', 'TER', 'QUA', 'QUI', 'SEX', 'SAB', 'DOM')` [name: 'chk_dia_semana']
  }
}

Table AVALIACAO {
  id_avaliacao INTEGER [pk]

  ds_avaliacao VARCHAR(255)
  qt_peso_avaliacao NUMBER(3,1) [not null]
  qt_nota_maxima_avaliacao NUMBER(4,2) [not null]
  dt_hr_avaliacao DATE [not null]
  cd_tipo_avaliacao NUMBER(4) [not null]

  id_turma INTEGER [not null]
}
Ref: AVALIACAO.id_turma > TURMA.id_turma

Table REGISTRO_AULA {
  dt_registro_aula DATE [not null, check: `dt_registro_aula=TRUNC(dt_registro_aula)`]
  id_grade_turma INTEGER [not null, ref: > GRADE_TURMA.id_grade_turma]

  indexes {
    (dt_registro_aula, id_grade_turma) [pk]
  }
}

Table AVALIACAO_RESULTADO {
  id_matricula INTEGER [not null, ref: > MATRICULA.id_matricula]
  id_avaliacao INTEGER [not null, ref: > AVALIACAO.id_avaliacao]
  qt_nota_avaliacao_aluno NUMBER(4,2) [not null]

  indexes {
    (id_avaliacao, id_matricula) [pk]
  }
}

Table ALUNO_REGISTRO_AULA {
  dt_registro_aula DATE [not null]
  id_grade_turma INTEGER [not null]
  id_matricula INTEGER [not null, Ref: > MATRICULA.id_matricula]

  indexes {
    (dt_registro_aula, id_grade_turma, id_matricula) [pk]
  }
}
Ref: ALUNO_REGISTRO_AULA.(dt_registro_aula, id_grade_turma)
    > REGISTRO_AULA.(dt_registro_aula, id_grade_turma)
