DROP SEQUENCE SQ_ALUNO;
DROP SEQUENCE SQ_PROFESSOR;
DROP SEQUENCE SQ_CURSO;
DROP SEQUENCE SQ_DISCIPLINA;
DROP SEQUENCE SQ_PERIODO_LETIVO;
DROP SEQUENCE SQ_TURMA;
DROP SEQUENCE SQ_MATRICULA;
DROP SEQUENCE SQ_GRADE_TURMA;
DROP SEQUENCE SQ_AVALIACAO;

DROP TABLE ALUNO_REGISTRO_AULA;
DROP TABLE AVALIACAO_RESULTADO;
DROP TABLE REGISTRO_AULA;
DROP TABLE AVALIACAO;
DROP TABLE GRADE_TURMA;
DROP TABLE MATRICULA;
DROP TABLE TURMA;
DROP TABLE PERIODO_LETIVO;
DROP TABLE GRADE_CURSO;
DROP TABLE DISCIPLINA_CURSO;
DROP TABLE DISCIPLINA;
DROP TABLE CURSO;
DROP TABLE PROFESSOR;
DROP TABLE ALUNO;

DROP TRIGGER trg_aluno_registro_aula_turma;
DROP TRIGGER trg_avaliacao_resultado_turma;
