DROP SEQUENCE SQ_ALUNO;
DROP SEQUENCE SQ_PROFESSOR;
DROP SEQUENCE SQ_CURSO;
DROP SEQUENCE SQ_DISCIPLINA;
DROP SEQUENCE SQ_COMPONENTE_CURRICULAR;
DROP SEQUENCE SQ_GRADE_CURSO;
DROP SEQUENCE SQ_PERIODO_LETIVO;
DROP SEQUENCE SQ_TURMA;
DROP SEQUENCE SQ_MATRICULA;
DROP SEQUENCE SQ_GRADE_TURMA;
DROP SEQUENCE SQ_AVALIACAO;

DROP PACKAGE BODY pk_banco_semestral;
DROP PACKAGE pk_banco_semestral;

DROP FUNCTION fn_media_notas;
DROP FUNCTION fn_percentual_frequencia;
DROP FUNCTION fn_situacao_aluno;
DROP FUNCTION fn_data_inicio_periodo_letivo;

DROP TABLE REGISTRO_AULA_MATRICULA;
DROP TABLE REGISTRO_AULA;
DROP TABLE AVALIACAO_RESULTADO;
DROP TABLE AVALIACAO;
DROP TABLE GRADE_TURMA;
DROP TABLE MATRICULA;
DROP TABLE TURMA;
DROP TABLE PERIODO_LETIVO;
DROP TABLE GRADE_CURSO;
DROP TABLE COMPONENTE_CURRICULAR;
DROP TABLE DISCIPLINA;
DROP TABLE CURSO;
DROP TABLE PROFESSOR;
DROP TABLE ALUNO;
